#!/usr/bin/env bash
# generated by yoke
# opencode-grind-loop.sh — Grind loop wrapper for headless/CI agent dispatch
#
# Features:
#   - Reads config from .agents/config.yaml
#   - Plan-first check before starting
#   - Stall timeout via `timeout` command
#   - Structured JSON parsing from check-completion.sh
#   - Session logging for post-hoc observability
#
# Usage (sourceable):
#   source .agents/hooks/opencode-grind-loop.sh
#   grind_loop "your prompt here"
#
# Or standalone:
#   bash .agents/hooks/opencode-grind-loop.sh "your prompt here"

set -euo pipefail

CONFIG_FILE=".agents/config.yaml"

read_config() {
    local key="$1"
    local default="$2"
    if [ -f "$CONFIG_FILE" ]; then
        local value
        value=$(grep -E "^\s+${key}:" "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*:[[:space:]]*//' | sed "s/[\"']//g" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || echo "")
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
    fi
    echo "$default"
}

MAX_ITERATIONS="${MAX_GRIND_ITERATIONS:-$(read_config max_iterations 5)}"
STALL_TIMEOUT=$(read_config stall_timeout_seconds 300)

check_plan_exists() {
    local plan_files
    plan_files=$(find docs/plans -maxdepth 1 \( -name "issue-*.md" -o -name "plan-*.md" -o -name "_PLAN_*.md" \) 2>/dev/null | head -1)
    if [ -z "$plan_files" ]; then
        echo ""
        echo "⚠️  PLAN-FIRST: No plan file found in docs/plans/"
        echo "   Before coding, create docs/plans/issue-{NUMBER}.md"
        echo "   Template: docs/templates/plan-template.md"
        echo ""
        return 1
    fi
    return 0
}

extract_followup() {
    local json="$1"
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r '.followup_prompt // empty' 2>/dev/null || echo "$json"
    else
        local prompt
        prompt=$(echo "$json" | grep -o '"followup_prompt":[[:space:]]*"[^"]*"' 2>/dev/null | sed 's/"followup_prompt":[[:space:]]*"//' | sed 's/"$//' || echo "")
        if [ -n "$prompt" ]; then
            echo -e "$prompt"
        else
            echo "$json"
        fi
    fi
}

grind_loop() {
    local prompt="${1:-}"
    if [ -z "$prompt" ]; then
        echo "Usage: grind_loop 'your prompt here'"
        return 1
    fi

    echo "━━━ GRIND LOOP CONFIG ━━━"
    echo "  Max iterations: $MAX_ITERATIONS"
    echo "  Stall timeout:  ${STALL_TIMEOUT}s"
    echo "  Config file:    $CONFIG_FILE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━"

    for i in $(seq 1 "$MAX_ITERATIONS"); do
        echo ""
        echo "━━━ GRIND LOOP: Iteration $i/$MAX_ITERATIONS ━━━"

        local agent_exit=0
        if [ "$STALL_TIMEOUT" -gt 0 ]; then
            timeout "${STALL_TIMEOUT}s" opencode run "$prompt" || agent_exit=$?
        else
            opencode run "$prompt" || agent_exit=$?
        fi

        if [ "$agent_exit" -eq 124 ]; then
            echo "━━━ GRIND LOOP: Agent stalled (no output for ${STALL_TIMEOUT}s). Re-prompting. ━━━"
            prompt="You appear to be stuck — the session timed out after ${STALL_TIMEOUT} seconds of inactivity. Check your current approach and try a different angle."
            continue
        fi

        export GRIND_ITERATION="$i"
        local check_output=""
        local check_exit=0
        check_output=$(bash .agents/hooks/check-completion.sh 2>/dev/null) || check_exit=$?

        if [ "$check_exit" -eq 0 ]; then
            echo "━━━ GRIND LOOP: Complete after $i iteration(s) ━━━"
            return 0
        fi

        if [ -n "$check_output" ]; then
            local followup
            followup=$(extract_followup "$check_output")
            if [ -n "$followup" ]; then
                prompt="$followup"
                echo ""
                echo "━━━ GRIND LOOP: Incomplete. Re-prompting: ━━━"
                echo "$followup" | head -5
                echo ""
            else
                echo "━━━ GRIND LOOP: check-completion returned non-zero but no follow-up. Stopping. ━━━"
                return 1
            fi
        else
            echo "━━━ GRIND LOOP: check-completion returned non-zero but no output. Stopping. ━━━"
            return 1
        fi
    done

    echo ""
    echo "━━━ GRIND LOOP: Max iterations ($MAX_ITERATIONS) reached. ━━━"
    return 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    grind_loop "$@"
fi
ENDOFFILE

