install_layer2_minimal() {
    echo ""
    echo "=== Layer 2: Core agentic loop (minimal) ==="

    # --- Directories ---
    create_dir ".agents/hooks"
    create_dir ".agents/commands"
    create_dir ".agents/agents/code-reviewer"
    create_dir ".agents/skills"
    create_dir "scripts"
    create_dir "docs/plans"

    # --- Static: .agents/config.yaml ---
    write_file ".agents/config.yaml" '# generated by yoke
# Shared agent harness configuration
# Read by: check-completion.sh, grind-loop.ts, opencode-grind-loop.sh
#
# Keep this flat and simple — shell scripts parse it with grep/awk.

grind_loop:
  max_iterations: 10
  # Stall timeout: agent alive but no progress (e.g., stuck LLM call)
  stall_timeout_seconds: 2400
  # Idle timeout: agent stopped working but did not finish
  idle_timeout_seconds: 120
  # Session log for post-hoc observability
  session_log: .agents/session-log.jsonl
  # Max session log lines before truncation
  session_log_max_lines: 200

scratchpad:
  path: .agents/scratchpad.md

orchestrator:
  max_parallel: 3
  poll_interval_seconds: 30
  stall_detection_multiplier: 2
  log: .agents/orchestrator-log.jsonl
  auto_merge_method: squash
  default_agent_tool: opencode
  default_label: orchestrator-ready
  kill_grace_seconds: 5'

    # --- Static: .agents/scratchpad.md ---
    write_file ".agents/scratchpad.md" '## STATUS: IDLE

## ITERATION: 0/10

## STARTED_AT:

## COMPLETED

- [ ] Plan file created
- [ ] Tests written
- [ ] Implementation done
- [ ] Code review passed

## CURRENT_FOCUS

## PREVIOUS_ATTEMPTS

## BLOCKERS

None'

    # --- Static: .agents/hooks/check-plan-exists.sh ---
    write_file ".agents/hooks/check-plan-exists.sh" '#!/usr/bin/env bash
# generated by yoke
# check-plan-exists.sh — PreToolUse hook for plan-first enforcement
# Checks that a plan file exists in docs/plans/ before allowing code writes.
#
# Exit codes:
#   0 = plan exists, proceed with tool use
#   1 = no plan found, deny tool use (message on stdout)

set -euo pipefail

# Allow writes to plan files themselves, docs, and non-code files
TOOL_PATH="${1:-}"
if [ -n "$TOOL_PATH" ]; then
    case "$TOOL_PATH" in
        docs/plans/*|docs/templates/*|.agents/*|.claude/*|.opencode/*|.kiro/*|*.md|*.json|*.toml|*.yaml|*.yml)
            exit 0
            ;;
    esac
fi

# Check if any plan file exists in docs/plans/ (excluding INDEX.md and templates)
PLAN_FILES=$(find docs/plans -maxdepth 1 -name "issue-*.md" -o -name "plan-*.md" -o -name "_PLAN_*.md" 2>/dev/null | head -1)

if [ -z "$PLAN_FILES" ]; then
    echo "DENIED: No plan file found in docs/plans/. Before writing code, create a plan:

1. Copy the template: docs/templates/plan-template.md
2. Save as: docs/plans/issue-{NUMBER}.md or docs/plans/_PLAN_issue-{NUMBER}.md
3. Fill in: goal, acceptance criteria, files to modify, test scenarios, risks

See docs/templates/plan-template.md for the format."
    exit 1
fi

exit 0'


    # --- Template: .agents/hooks/check-completion.sh ---
    write_template_heredoc ".agents/hooks/check-completion.sh" << 'ENDOFFILE'
#!/usr/bin/env bash
# generated by yoke
# check-completion.sh — Shared completion checker for grind loop
# Used by: Claude Code Stop hook, OpenCode grind-loop.ts, opencode-grind-loop.sh
#
# Exit codes:
#   0 = all done, no follow-up needed
#   1 = incomplete, structured JSON on stdout, diagnostics on stderr
#
# Environment:
#   GRIND_ITERATION (default: 0) — current iteration count
#   MAX_GRIND_ITERATIONS — override max iterations (optional)
#
# Output (stdout): JSON object with completion status and follow-up prompt
# Output (stderr): Human-readable diagnostic messages

set -euo pipefail

# --- Config reading ---

CONFIG_FILE=".agents/config.yaml"

read_config() {
    local key="$1"
    local default="$2"
    if [ -f "$CONFIG_FILE" ]; then
        local value
        value=$(grep -E "^\s+${key}:" "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*:[[:space:]]*//' | sed "s/[\"']//g" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || echo "")
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
    fi
    echo "$default"
}

MAX_ITERATIONS="${MAX_GRIND_ITERATIONS:-$(read_config max_iterations 5)}"
CURRENT_ITERATION="${GRIND_ITERATION:-0}"
SESSION_LOG=$(read_config session_log ".agents/session-log.jsonl")
SESSION_LOG_MAX=$(read_config session_log_max_lines 200)
SCRATCHPAD=$(read_config path ".agents/scratchpad.md")

# --- Helpers ---

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
CHECKS_TESTS_PASS=true
CHECKS_REVIEW_CLEAN=true
CHECKS_REVIEW_EXISTS=false
CHECKS_SCRATCHPAD_DONE=false
FAILED_CHECKS=()
FAILED_TESTS_LIST=""
SCRATCHPAD_STATUS=""
SCRATCHPAD_FOCUS=""
FOLLOWUP_PROMPT=""

read_scratchpad() {
    if [ ! -f "$SCRATCHPAD" ]; then
        return
    fi
    SCRATCHPAD_STATUS=$(grep -E "^## STATUS:" "$SCRATCHPAD" 2>/dev/null | sed 's/## STATUS:[[:space:]]*//' || echo "")
    SCRATCHPAD_FOCUS=$(grep -A1 "^## CURRENT_FOCUS" "$SCRATCHPAD" 2>/dev/null | tail -1 | sed 's/^[[:space:]]*//' || echo "")
    if [ "$SCRATCHPAD_FOCUS" = "## CURRENT_FOCUS" ] || [ -z "$SCRATCHPAD_FOCUS" ]; then
        SCRATCHPAD_FOCUS=""
    fi
}

json_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    echo "$s"
}

output_json() {
    local complete="$1"
    local escaped_prompt
    escaped_prompt=$(json_escape "$FOLLOWUP_PROMPT")
    local escaped_focus
    escaped_focus=$(json_escape "$SCRATCHPAD_FOCUS")
    local escaped_status
    escaped_status=$(json_escape "$SCRATCHPAD_STATUS")
    local escaped_tests
    escaped_tests=$(json_escape "$FAILED_TESTS_LIST")

    local failed_json="[]"
    if [ ${#FAILED_CHECKS[@]} -gt 0 ]; then
        failed_json="["
        local first=true
        for check in "${FAILED_CHECKS[@]}"; do
            if [ "$first" = true ]; then first=false; else failed_json+=","; fi
            failed_json+="\"$check\""
        done
        failed_json+="]"
    fi

    cat <<ENDJSON
{
  "complete": $complete,
  "iteration": $CURRENT_ITERATION,
  "max_iterations": $MAX_ITERATIONS,
  "timestamp": "$TIMESTAMP",
  "checks": {
    "tests_pass": $CHECKS_TESTS_PASS,
    "review_clean": $CHECKS_REVIEW_CLEAN,
    "review_exists": $CHECKS_REVIEW_EXISTS,
    "scratchpad_done": $CHECKS_SCRATCHPAD_DONE
  },
  "failed_checks": $failed_json,
  "followup_prompt": "$escaped_prompt",
  "context": {
    "failed_tests": "$escaped_tests",
    "scratchpad_status": "$escaped_status",
    "scratchpad_focus": "$escaped_focus"
  }
}
ENDJSON
}

append_session_log() {
    local complete="$1"
    local log_dir
    log_dir=$(dirname "$SESSION_LOG")
    mkdir -p "$log_dir" 2>/dev/null || true

    local failed_json="[]"
    if [ ${#FAILED_CHECKS[@]} -gt 0 ]; then
        failed_json="["
        local first=true
        for check in "${FAILED_CHECKS[@]}"; do
            if [ "$first" = true ]; then first=false; else failed_json+=","; fi
            failed_json+="\"$check\""
        done
        failed_json+="]"
    fi

    local escaped_status
    escaped_status=$(json_escape "$SCRATCHPAD_STATUS")

    echo "{\"timestamp\":\"$TIMESTAMP\",\"iteration\":$CURRENT_ITERATION,\"complete\":$complete,\"failed\":$failed_json,\"scratchpad_status\":\"$escaped_status\"}" >> "$SESSION_LOG" 2>/dev/null || true

    if [ -f "$SESSION_LOG" ]; then
        local line_count
        line_count=$(wc -l < "$SESSION_LOG" 2>/dev/null | tr -d ' ' || echo "0")
        if [ "$line_count" -gt "$SESSION_LOG_MAX" ]; then
            tail -n "$SESSION_LOG_MAX" "$SESSION_LOG" > "${SESSION_LOG}.tmp" 2>/dev/null && mv "${SESSION_LOG}.tmp" "$SESSION_LOG" 2>/dev/null || true
        fi
    fi
}

fail_with_prompt() {
    FOLLOWUP_PROMPT="$1"
    append_session_log "false"
    output_json "false"
    exit 1
}

# --- Read scratchpad ---

read_scratchpad

# --- Iteration cap ---

if [ "$CURRENT_ITERATION" -ge "$MAX_ITERATIONS" ]; then
    echo "GRIND_LOOP: Max iterations ($MAX_ITERATIONS) reached. Stopping." >&2
    append_session_log "true"
    output_json "true"
    exit 0
fi

# --- Check 0: Verify work has been done ---

MERGE_BASE=$(git merge-base HEAD main 2>/dev/null || echo "")
if [ -n "$MERGE_BASE" ]; then
    COMMITS_AHEAD=$(git rev-list --count "$MERGE_BASE..HEAD" 2>/dev/null | tr -d ' \n' || echo "0")
    if [ "$COMMITS_AHEAD" -eq 0 ]; then
        fail_with_prompt "No commits found beyond the merge base. Start working on the task — create a plan, write tests, and implement the solution."
    fi
fi

# --- Check 1: Tests pass ---

echo "GRIND_LOOP: Checking tests..." >&2
TEST_EXIT=0
TEST_OUTPUT=$({{test_command}} 2>&1) || TEST_EXIT=$?
if [ "$TEST_EXIT" -ne 0 ]; then
    CHECKS_TESTS_PASS=false
    FAILED_CHECKS+=("tests_pass")
    FAILED_TESTS_LIST=$(echo "$TEST_OUTPUT" | grep -E "^FAILED" | head -5)
    TEST_TAIL=$(echo "$TEST_OUTPUT" | tail -20)

    local_prompt="Tests are still failing. Fix these failures and re-run:"
    local_prompt+="\n\n${FAILED_TESTS_LIST}"
    local_prompt+="\n\nTest output (last 20 lines):\n${TEST_TAIL}"

    if [ -n "$SCRATCHPAD_FOCUS" ]; then
        local_prompt+="\n\nYou were working on: ${SCRATCHPAD_FOCUS}"
        local_prompt+="\nContinue from where you left off."
    fi

    fail_with_prompt "$local_prompt"
fi

# --- Check 2: Code review findings ---

REVIEW_FILES=$(find . -maxdepth 1 -name "CODE_REVIEW_*.md" 2>/dev/null || echo "")
if [ -n "$REVIEW_FILES" ]; then
    CHECKS_REVIEW_EXISTS=true
    for review_file in $REVIEW_FILES; do
        UNRESOLVED=$(grep -iE "^##.*critical|^##.*high|\*\*severity\*\*:.*critical|\*\*severity\*\*:.*high|\*\*Priority\*\*:.*Critical|\*\*Priority\*\*:.*High" "$review_file" 2>/dev/null | grep -viE "✅|FIXED|Resolved|was ◆" || true)
        if [ -n "$UNRESOLVED" ]; then
            CHECKS_REVIEW_CLEAN=false
            FAILED_CHECKS+=("review_clean")
            FINDINGS=$(echo "$UNRESOLVED" | head -5)

            local_prompt="CODE_REVIEW has unresolved Critical/High findings in $review_file:"
            local_prompt+="\n\n${FINDINGS}"
            local_prompt+="\n\nAddress these findings, then re-run the code reviewer."

            fail_with_prompt "$local_prompt"
        fi
    done
fi

# --- Check 3: Blind review needed ---

PR_EXISTS=$(gh pr list --head "$(git branch --show-current)" --json number --jq '.[0].number' 2>/dev/null || echo "")
if [ -n "$PR_EXISTS" ] && [ -z "$REVIEW_FILES" ]; then
    CHANGED_FILES=$(git diff --name-only "$(git merge-base HEAD main)..HEAD" 2>/dev/null || echo "")
    IS_TRIVIAL=true
    while IFS= read -r file; do
        [ -z "$file" ] && continue
        case "$file" in
            *.md|*.txt|*.json|*.toml|*.yaml|*.yml|*.lock) ;;
            *) IS_TRIVIAL=false; break ;;
        esac
    done <<< "$CHANGED_FILES"

    if [ "$IS_TRIVIAL" = false ]; then
        ITERATIONS_LEFT=$((MAX_ITERATIONS - CURRENT_ITERATION))
        URGENCY=""
        if [ "$ITERATIONS_LEFT" -le 3 ]; then
            URGENCY="URGENT (only $ITERATIONS_LEFT iterations left): "
        fi
        FAILED_CHECKS+=("review_exists")
        fail_with_prompt "${URGENCY}EXECUTE THIS NOW (do not check PR status, do not wait):
1. Use the code-reviewer subagent to review PR #$PR_EXISTS
2. The code review will create a CODE_REVIEW_*.md file
3. After review, fix any Critical/High findings
4. Re-run the code reviewer to verify fixes

Do this immediately. Do not skip this step."
    fi
fi

# --- Check 4: Scratchpad signals DONE ---

if [ -f "$SCRATCHPAD" ]; then
    if grep -q "STATUS: DONE" "$SCRATCHPAD" 2>/dev/null; then
        CHECKS_SCRATCHPAD_DONE=true
        echo "GRIND_LOOP: Scratchpad signals DONE." >&2
    fi
fi

# --- Check 5: Agent idle detection ---

if [ "$SCRATCHPAD_STATUS" = "IN_PROGRESS" ] && [ "$CHECKS_SCRATCHPAD_DONE" = false ]; then
    UNCHECKED=$(grep -c "\- \[ \]" "$SCRATCHPAD" 2>/dev/null || echo "0")
    if [ "$UNCHECKED" -gt 0 ]; then
        STUCK_PROMPT=""
        if [ -f "$SESSION_LOG" ] && [ -n "$SCRATCHPAD_FOCUS" ]; then
            RECENT_SAME_FOCUS=$(tail -3 "$SESSION_LOG" 2>/dev/null | grep -c "$(json_escape "$SCRATCHPAD_FOCUS")" 2>/dev/null || echo "0")
            if [ "$RECENT_SAME_FOCUS" -ge 2 ]; then
                STUCK_PROMPT="\n\nYou have been stuck on the same task for $RECENT_SAME_FOCUS iterations. Try a different approach — simplify, break it into smaller steps, or reconsider the design."
            fi
        fi

        local_prompt="You stopped working but the task is not complete. The scratchpad shows $UNCHECKED unchecked items remaining."
        if [ -n "$SCRATCHPAD_FOCUS" ]; then
            local_prompt+="\n\nYou were working on: ${SCRATCHPAD_FOCUS}"
        fi
        local_prompt+="\n\nContinue from where you left off. Update the scratchpad as you make progress."
        if [ -n "$STUCK_PROMPT" ]; then
            local_prompt+="$STUCK_PROMPT"
        fi

        FAILED_CHECKS+=("agent_idle")
        fail_with_prompt "$local_prompt"
    fi
fi

# --- All checks passed ---

echo "GRIND_LOOP: All checks passed." >&2
append_session_log "true"
output_json "true"
exit 0
ENDOFFILE


    # --- Template: .agents/hooks/opencode-grind-loop.sh ---
    write_template_heredoc ".agents/hooks/opencode-grind-loop.sh" << 'ENDOFFILE'
#!/usr/bin/env bash
# generated by yoke
# opencode-grind-loop.sh — Grind loop wrapper for headless/CI agent dispatch
#
# Features:
#   - Reads config from .agents/config.yaml
#   - Plan-first check before starting
#   - Stall timeout via `timeout` command
#   - Structured JSON parsing from check-completion.sh
#   - Session logging for post-hoc observability
#
# Usage (sourceable):
#   source .agents/hooks/opencode-grind-loop.sh
#   grind_loop "your prompt here"
#
# Or standalone:
#   bash .agents/hooks/opencode-grind-loop.sh "your prompt here"

set -euo pipefail

CONFIG_FILE=".agents/config.yaml"

read_config() {
    local key="$1"
    local default="$2"
    if [ -f "$CONFIG_FILE" ]; then
        local value
        value=$(grep -E "^\s+${key}:" "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*:[[:space:]]*//' | sed "s/[\"']//g" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || echo "")
        if [ -n "$value" ]; then
            echo "$value"
            return
        fi
    fi
    echo "$default"
}

MAX_ITERATIONS="${MAX_GRIND_ITERATIONS:-$(read_config max_iterations 10)}"

check_plan_exists() {
    local plan_files
    plan_files=$(find docs/plans -maxdepth 1 \( -name "issue-*.md" -o -name "plan-*.md" -o -name "_PLAN_*.md" \) 2>/dev/null | head -1)
    if [ -z "$plan_files" ]; then
        echo ""
        echo "⚠️  PLAN-FIRST: No plan file found in docs/plans/"
        echo "   Before coding, create docs/plans/issue-{NUMBER}.md"
        echo "   Template: docs/templates/plan-template.md"
        echo ""
        return 1
    fi
    return 0
}

extract_followup() {
    local json="$1"
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r '.followup_prompt // empty' 2>/dev/null || echo "$json"
    else
        local prompt
        prompt=$(echo "$json" | grep -o '"followup_prompt":[[:space:]]*"[^"]*"' 2>/dev/null | sed 's/"followup_prompt":[[:space:]]*"//' | sed 's/"$//' || echo "")
        if [ -n "$prompt" ]; then
            echo -e "$prompt"
        else
            echo "$json"
        fi
    fi
}

grind_loop() {
    local prompt="${1:-}"
    if [ -z "$prompt" ]; then
        echo "Usage: grind_loop 'your prompt here'"
        return 1
    fi

    # Ensure headless permissions for opencode
    mkdir -p .opencode
    cat > .opencode/config.json <<EOFCONFIG
{
  "permissions": {
    "external_directory": "allow",
    "bash": "allow",
    "read": "allow",
    "write": "allow",
    "edit": "allow"
  },
  "bash": {
    "timeout": 300000
  }
}
EOFCONFIG

    echo "━━━ GRIND LOOP CONFIG ━━━"
    echo "  Max iterations: $MAX_ITERATIONS"
    echo "  Config file:    $CONFIG_FILE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━"

    for i in $(seq 1 "$MAX_ITERATIONS"); do
        echo ""
        echo "━━━ GRIND LOOP: Iteration $i/$MAX_ITERATIONS ━━━"

        local agent_exit=0
        opencode run "$prompt" || agent_exit=$?

        # Auto-commit so next iteration sees progress via git
        git add -A 2>/dev/null || true
        git diff --cached --quiet 2>/dev/null || git commit -m "wip: grind loop iteration $i" 2>/dev/null || true

        export GRIND_ITERATION="$i"
        local check_output=""
        local check_exit=0
        check_output=$(bash .agents/hooks/check-completion.sh 2>/dev/null) || check_exit=$?

        if [ "$check_exit" -eq 0 ]; then
            echo "━━━ GRIND LOOP: Complete after $i iteration(s) ━━━"
            return 0
        fi

        if [ -n "$check_output" ]; then
            local followup
            followup=$(extract_followup "$check_output")
            if [ -n "$followup" ]; then
                prompt="$1

━━━ ITERATION CONTEXT ━━━
This is iteration $i of $MAX_ITERATIONS.

IMPORTANT: $followup

Continue working until the task is complete."
                echo ""
                echo "━━━ GRIND LOOP: Incomplete. Re-prompting: ━━━"
                echo "$followup" | head -5
                echo ""
            else
                echo "━━━ GRIND LOOP: check-completion returned non-zero but no follow-up. Stopping. ━━━"
                return 1
            fi
        else
            echo "━━━ GRIND LOOP: check-completion returned non-zero but no output. Stopping. ━━━"
            return 1
        fi
    done

    echo ""
    echo "━━━ GRIND LOOP: Max iterations ($MAX_ITERATIONS) reached. ━━━"
    return 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    grind_loop "$@"
fi
ENDOFFILE

}


# ============================================================================
# LAYER 2+3 — STANDARD PROFILE (standard and full get these)
# ============================================================================

