install_layer2_standard() {
    echo ""
    echo "=== Layer 2+3: Commands, code reviewer, docs, CI (standard) ==="

    # --- Directories ---
    create_dir "docs/dev"
    create_dir "docs/templates"
    create_dir "docs/architecture/decisions"

    # --- Template: .agents/commands/start-issue.md ---
    write_template ".agents/commands/start-issue.md" '<!-- generated by yoke -->
# Start Issue Command

Start work on a GitHub issue.

## Usage

```
/start-issue <issue_number>
```

**Arguments:**

- `issue_number`: The GitHub issue number to work on

## Argument Indexing

- **Claude Code**: Use `$1` for the first argument (issue number)
- **OpenCode**: Use `$ARGUMENTS` to get all arguments

## Steps

### 0. Preflight Check

Run issue-preflight.sh to validate the issue is ready:

```bash
bash scripts/issue-preflight.sh <issue_number>
```

If it exits non-zero, report the block reason from the JSON output and stop.

### 1. Get Repo Info

```bash
git remote get-url origin
```

Parse owner and repo name from the output.

### 2. Fetch Issue

```bash
gh issue view <issue_number> --repo <owner>/<repo>
```

### 3. Verify/Create Branch

```bash
git branch --show-current
```

If not on correct branch:

```bash
git checkout -b feature/issue-<issue_number>-<short-description>
```

### 4. Create Plan File

Create `docs/plans/_PLAN_issue-{issue_number}.md` using the template at `docs/templates/plan-template.md`.

### 5. Scaffold Test File

Create test file in `tests/` with basic structure.

### 6. Verify Tests Run

```bash
{{test_command}}
```

### 7. Trigger Code Review

Once done, call code-review sub-agent and enter a review-fix loop until review states PR is ready.

## Notes

- This command is for starting NEW work on an issue
- If work is already in progress, skip this command'

    # --- Template: .agents/commands/create-pr.md ---
    write_template ".agents/commands/create-pr.md" '<!-- generated by yoke -->
# Create PR Command

Create a pull request after completing feature work.

## Usage

```
/create-pr
```

## Argument Indexing

- **Claude Code**: No arguments needed
- **OpenCode**: No arguments needed

## Steps

### 1. Run Tests

```bash
{{test_command}}
```

### 2. Run Linting

```bash
{{lint_command}}
{{format_command}}
```

### 3. Run Type Checking

```bash
{{typecheck_command}}
```

### 4. Get Repo Info

```bash
git remote get-url origin
```

Parse owner and repo name.

### 5. Check Changes

```bash
git status
git diff --cached
```

### 6. Commit if Needed

```bash
git add -A
git commit -m "feat(scope): description for #XX"
```

### 7. Push Branch

```bash
git push -u origin <branch-name>
```

### 8. Create PR

```bash
gh pr create --repo <owner>/<repo> \
  --title "feat(scope): description for #XX" \
  --head <branch-name> \
  --base main \
  --body "## Summary\n<description>\n\n## Issue\nCloses #XX"
```

### 9. Trigger Code Review

Invoke the code-reviewer subagent with issue number, PR number, owner, repo, and feature description.

### 10. Report Completion

Reply to user with PR URL and plan reference.

## Notes

- Ensure all tests pass before creating PR
- Include issue number in commit message and PR title
- Always trigger code review (mandatory)'

    # --- Template: .agents/commands/fix-issue.md ---
    write_template ".agents/commands/fix-issue.md" '<!-- generated by yoke -->
# Fix Issue Command

Fetch issue details, find relevant code, implement fix, and open PR.

## Usage

```
/fix-issue <issue_number>
```

**Arguments:**

- `issue_number`: The GitHub issue number to fix

## Argument Indexing

- **Claude Code**: Use `$1` for the first argument (issue number)
- **OpenCode**: Use `$ARGUMENTS` to get all arguments

## Steps

### 1. Get Repo Info

```bash
git remote get-url origin
```

### 2. Fetch Issue

```bash
gh issue view <issue_number> --repo <owner>/<repo>
```

### 3. Analyze Issue

Read the issue description and identify what needs fixing.

### 4. Find Relevant Code

Search for relevant code in the source directory.

### 5. Create Branch

```bash
git checkout -b fix/issue-<issue_number>-<short-description>
```

### 6. Write Test First

Create test that reproduces the issue. Run test to confirm it fails.

### 7. Implement Fix

Implement the fix to make the test pass.

### 8. Run Tests

```bash
{{test_command}}
```

### 9. Run Linting

```bash
{{lint_command}}
{{format_command}}
```

### 10. Run Type Checking

```bash
{{typecheck_command}}
```

### 11. Commit

```bash
git add -A
git commit -m "fix(scope): description for #XX"
```

### 12. Push and Create PR

```bash
git push -u origin fix/issue-XX-description
gh pr create --repo <owner>/<repo> \
  --title "fix(scope): description for #XX" \
  --head fix/issue-XX-description \
  --base main \
  --body "## Summary\n<description>\n\n## Issue\nFixes #XX"
```

### 13. Trigger Code Review

Invoke the code-reviewer subagent.

## Notes

- Use `fix/` prefix for bug fix branches
- Always write test first (TDD)
- Include issue number in commit and PR'

    # --- Template: .agents/commands/plan-feature.md ---
    write_template ".agents/commands/plan-feature.md" '<!-- generated by yoke -->
# Plan Feature Command

Decompose a high-level feature into well-formed, agent-sized GitHub issues with dependency ordering and Agent Metadata — ready for the orchestrator.

## Usage

```
/plan-feature <feature_description>
```

**Arguments:**

- `feature_description`: A natural-language description of the feature to plan. Can be a sentence, a paragraph, or a reference to an existing issue/doc.

## Argument Indexing

- **Claude Code**: Use `$1` for the first argument (feature description, may be multi-word)
- **OpenCode**: Use `$ARGUMENTS` to get all arguments

## Steps

### 1. Get Repo Info

```bash
git remote get-url origin
```

Parse owner and repo name.

### 2. Understand the Codebase Context

Read the key context files to understand what exists:

- `AGENTS.md` — architecture overview, component locations
- `docs/architecture/overview.md` — module structure, layering rules
- `docs/principles.md` — code invariants (if exists)

Scan the source directory to understand the current module structure.

### 3. Analyze the Feature

Break the feature description into concrete work items. For each, determine:

- **What changes**: Which files/modules are affected
- **Scope**: Is this a new module, modification to existing, or cross-cutting?
- **Complexity**: small (< 1 hour agent work), medium (1-3 hours), large (needs further decomposition)
- **Dependencies**: Does this require another piece to land first?
- **Parallel safety**: Can an agent work on this while other agents work on sibling issues?

### 4. Decomposition Rules

Follow the issue-decomposition skill at `.agents/skills/issue-decomposition/SKILL.md` for:

- Right granularity (one issue = one agent session = one worktree)
- Dependency patterns (data models before consumers, infrastructure before features)
- Parallel safety rules
- Acceptance criteria rules (specific, testable, complete, independent)

### 5. Build the Dependency Graph

Arrange issues into a dependency DAG:

- Identify which issues block which others
- Group independent issues that can run in parallel (same wave)
- Verify there are no cycles
- Verify the graph is connected (no orphans)

Present the graph as waves:

```
Wave 1 (parallel): #A Data models, #B Config schema
Wave 2 (parallel): #C Service layer (depends on #A), #D CLI commands (depends on #B)
Wave 3: #E Integration tests (depends on #C, #D)
```

### 6. Present the Plan to the Developer

Show the complete plan with issue breakdown per wave, including title, description, acceptance criteria, files, complexity, dependencies, and parallel safety for each issue.

Include the dependency graph and the orchestrator command to run after issues are created.

### 7. Wait for Developer Approval

**STOP HERE.** Ask the developer:

> "Here'\''s the proposed breakdown into N issues across M waves. Want me to:
> 1. Create all issues as-is
> 2. Modify the plan (tell me what to change)
> 3. Cancel"

**Do NOT create issues without explicit approval.**

### 8. Create Issues

Once approved, create each issue via `gh`:

```bash
gh issue create --repo <owner>/<repo> \
  --title "<title>" \
  --label "orchestrator-ready" \
  --body "## Description

<description>

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2

## Agent Metadata

| Field                | Value              |
| -------------------- | ------------------ |
| Depends on           | #<dep1>, #<dep2>   |
| Parallel safe        | yes                |
| Auto-merge           | no                 |
| Agent tool           | opencode           |
| Estimated complexity | small              |
"
```

Create issues in dependency order (Wave 1 first) so that `Depends on` fields can reference real issue numbers.

### 9. Report Summary

After all issues are created, report the issue list with wave assignments and the orchestrator command.

## Notes

- This command is for PLANNING, not implementation. It creates issues; agents implement them later.
- Always wait for developer approval before creating issues.
- Default to `Auto-merge: no` unless the developer explicitly says otherwise.
- Default to `Agent tool: opencode` unless the developer specifies otherwise.
- If the feature is too large to decompose in one pass (> 15 issues), suggest breaking it into sub-features first.'

    # --- Template: .agents/skills/issue-decomposition/SKILL.md ---
    write_template ".agents/skills/issue-decomposition/SKILL.md" '<!-- generated by yoke -->
---
name: issue-decomposition
description: Decompose features into well-formed, agent-sized GitHub issues with dependency ordering and orchestrator metadata
---

# Issue Decomposition Skill

How to break features into issues that the orchestrator can dispatch to agents effectively.

## Scope

This skill produces GitHub issues, not code. Output goes to `gh issue create` commands.

## The Right Granularity

An agent-sized issue has these properties:

- **One session**: An agent can complete it in a single worktree session (typically 1-5 grind loop iterations)
- **Focused scope**: Touches 1-4 files across 1-2 modules. If it touches more, split it.
- **Testable**: You can write a concrete test that verifies the issue is done
- **Independent merge**: The PR can be merged without waiting for unrelated work
- **Clear boundaries**: Another agent working on a sibling issue won'\''t have merge conflicts

### Size Guide

| Complexity | Agent time | Typical scope | Examples |
|---|---|---|---|
| small | < 30 min | 1-2 files, single module | Add a config field, write a utility function, fix a bug |
| medium | 30 min - 2 hours | 2-4 files, 1-2 modules | New strategy implementation, new API endpoint, new scanner |
| large | > 2 hours | 5+ files, 3+ modules | **Must be decomposed further** |

## Dependency Patterns

### Common Dependency Chains

```
Data model → Service that uses it → CLI/API that exposes it → Integration test
Config schema → Feature that reads config → Tests
Shared utility → Multiple consumers (parallel after utility lands)
```

### When to Use Dependencies

- **Use `Depends on`** when Issue B literally cannot start until Issue A'\''s PR is merged (e.g., B imports a class that A creates)
- **Don'\''t use `Depends on`** for soft ordering preferences. If B could technically start before A merges (maybe with a stub), they'\''re parallel-safe.
- **Minimize dependency depth**. A chain of A→B→C→D→E means 5 sequential waves. Look for ways to parallelize.

### Parallel Safety

Mark `Parallel safe: yes` when:
- The issue touches files that no sibling issue in the same wave touches
- The issue creates new files (no merge conflict possible)
- The issue modifies isolated sections of shared files (rare — default to `no` if unsure)

Mark `Parallel safe: no` when:
- Two issues in the same wave modify the same file
- The issue modifies a shared config or schema that others also modify

## Agent Metadata Reference

Every issue must include this table in the body:

```markdown
## Agent Metadata

| Field                | Value              |
| -------------------- | ------------------ |
| Depends on           | #42, #43           |
| Parallel safe        | yes                |
| Auto-merge           | no                 |
| Agent tool           | opencode           |
| Estimated complexity | small              |
```

### Field Rules

| Field | Values | Default | Notes |
|---|---|---|---|
| Depends on | `#none` or comma-separated issue numbers | `#none` | Use real issue numbers, not titles |
| Parallel safe | `yes` / `no` | `yes` | `no` if same-wave issues touch same files |
| Auto-merge | `yes` / `no` | `no` | Only `yes` for low-risk, well-tested changes |
| Agent tool | `opencode` / `claude` / `codex` / `kiro` | `opencode` | Which agent runtime to use |
| Estimated complexity | `small` / `medium` | `small` | `large` means "decompose further" |

## Acceptance Criteria Rules

Good acceptance criteria are:
- **Specific**: "Function `calculate_risk()` returns a `RiskScore` with `value` between 0.0 and 1.0" — not "implement risk calculation"
- **Testable**: Each criterion maps to at least one test case
- **Complete**: If all criteria pass, the issue is done. No hidden requirements.
- **Independent**: Each criterion can be verified on its own

### Anti-patterns

- Do not use vague criteria like "Implement the feature" or "Code is clean"
- Do not use subjective criteria like "Works correctly" or "All edge cases handled"

### Good examples

- "`SentimentScanner.scan()` returns `list[Opportunity]` with `score` field populated from LLM response"
- "Config file `config.yaml` is validated on load; missing required fields raise `ConfigError` with field name in message"
- "Test `test_momentum_strategy_buy_signal` passes: given 3 consecutive green candles with volume > 1.5x average, strategy returns BUY signal"

## Steps for Decomposition

1. **Read the feature description** — understand the full scope
2. **Identify the modules** — which parts of the codebase are affected? Check `AGENTS.md` architecture table.
3. **Find the natural seams** — where can you draw boundaries between independent units of work?
4. **Order by dependency** — data models first, then services, then consumers, then integration
5. **Estimate complexity** — if anything is "large", split it further
6. **Check parallel safety** — which issues in the same wave touch the same files?
7. **Write acceptance criteria** — concrete, testable, complete
8. **Build the wave plan** — group into waves respecting dependencies
9. **Verify the graph** — no cycles, no orphans, minimal depth

## Reference Files

| File | Purpose |
|---|---|
| `.github/ISSUE_TEMPLATE/feature-task.md` | Issue template with Agent Metadata table |
| `.agents/commands/plan-feature.md` | Command that uses this skill |
| `scripts/orchestrate.sh` | Orchestrator that consumes the issues |
| `scripts/issue-preflight.sh` | Validates issue readiness and parses metadata |
| `.agents/config.yaml` | Orchestrator config (max_parallel, default_agent_tool) |'


    # --- Template: .agents/agents/code-reviewer/prompt.md ---
    write_template ".agents/agents/code-reviewer/prompt.md" '<!-- generated by yoke -->
You are a code reviewer for {{repo_name}} — {{tech_stack}}.

## Your Task

Review the code changes and write findings to `CODE_REVIEW_{ISSUE_NUMBER}.md` in root directory.

This can be invoked in two contexts:

1. **Local changes** (no PR yet): Review uncommitted changes on the current branch
2. **PR review**: Review an existing pull request

## Required Information

From the invoking agent:

- `ISSUE_NUMBER` - GitHub issue number
- `PR_NUMBER` - Pull request number (optional for local review)
- `OWNER` - Repository owner
- `REPO` - Repository name
- `FEATURE_DESCRIPTION` - What was implemented

## Review Process

### For Local Changes (no PR):

1. Get local changes: `git status`, `git diff`, `git diff --cached`
2. Review against checklist below
3. Write findings to `CODE_REVIEW_{ISSUE_NUMBER}.md`

### For PR Review:

1. Get PR details: `gh pr view/diff {PR_NUMBER} --repo {OWNER}/{REPO}`
2. Review against checklist below
3. Write findings to `CODE_REVIEW_{ISSUE_NUMBER}.md`

## Review Checklist

### Golden Rules (from AGENTS.md)

- GitHub issue exists and is referenced
- Tests written first and updated for every change
- One feature/fix per PR with focused commits
- No secrets in code; use environment variables

### Focus Areas

**1. Correctness**
- Business logic validates against requirements
- Edge cases handled (null, empty, large inputs)
- Error paths with helpful responses

**2. Test-First Coverage**
- Tests present for all changes
- Deterministic tests (no random data)
- External APIs properly mocked

**3. Type Safety**
- No `Any` types without justification
- Explicit return types for exports

**4. Architecture**
- Changes respect module boundaries in `{{source_dir}}`
- No cross-layer imports that violate architecture rules

**5. Security**
- No hardcoded API keys or secrets
- Environment variables for all credentials
- Input validation at trust boundaries

**6. Git Hygiene**
- Conventional commits referencing issue
- Single intent per PR

### Auto-Block Criteria

1. Hardcoded secrets or committed env files with credentials
2. Missing tests for code changes
3. Lint or type check errors
4. No issue reference in PR/commits
5. Multiple unrelated features in PR

### Auto-Approve Candidates

1. Documentation-only changes
2. Dependency bumps (with passing tests)
3. Config tweaks without behavior changes
4. Test-only additions

## Output Format

Write to `CODE_REVIEW_{ISSUE_NUMBER}.md`:

```markdown
# Code Review for {FEATURE_DESCRIPTION}

**PR**: {PR_URL}
**Issue**: #{ISSUE_NUMBER}

## Overview

Brief description of changes and files involved.

## Suggestions

### {type_marker} {Summary with context}

- **Priority**: {Critical / High / Medium / Low}
- **File**: `{path/to/file}:{line}`
- **Details**: Explanation
- **Suggested Change** (if applicable):

## Summary

**Ready to merge?**: [Yes / No / With fixes]
**Reasoning**: 1-2 sentence assessment.
```

## Suggestion Markers

**Type:** △ Change, ‽ Question, · Nitpick, ↻ Refactor, ⚠ Concern, ✓ Positive, ※ Note, → Future

**Priority:** ■ Critical, ◆ High, ◇ Medium, ◦ Low'

    # --- Template: scripts/validate_docs.sh ---
    write_template "scripts/validate_docs.sh" '#!/usr/bin/env bash
# generated by yoke
# validate_docs.sh — Validate documentation cross-references
# Scans AGENTS.md, skill files, and docs for broken links to files that do not exist.

set -euo pipefail

VIOLATIONS=0

check_file() {
    local filepath="$1"
    local line_num=0
    while IFS= read -r line; do
        line_num=$((line_num + 1))
        # Markdown links: [text](path)
        echo "$line" | grep -oE '"'"'\[[^]]*\]\([^)]+\)'"'"' | while read -r match; do
            target=$(echo "$match" | sed '"'"'s/.*](\(.*\))/\1/'"'"')
            case "$target" in http://*|https://*|"#"*|mailto:*) continue ;; esac
            # Strip anchor fragments
            target="${target%%#*}"
            [ -z "$target" ] && continue
            resolved="$(dirname "$filepath")/$target"
            if [ ! -e "$resolved" ]; then
                echo "$filepath:$line_num: broken-link: Target \"$target\" does not exist. Remediation: Update the link or create the missing file."
                VIOLATIONS=$((VIOLATIONS + 1))
            fi
        done
        # Backtick paths: `path/to/file.ext`
        echo "$line" | grep -oE '"'"'`[^`]+\.[a-zA-Z]+`'"'"' | tr -d '"'"'`'"'"' | while read -r candidate; do
            case "$candidate" in http://*|https://*) continue ;; esac
            echo "$candidate" | grep -q "/" || continue
            candidate="${candidate%%#*}"
            if [ ! -e "$candidate" ]; then
                echo "$filepath:$line_num: broken-link: Target \"$candidate\" does not exist. Remediation: Update the link or create the missing file."
                VIOLATIONS=$((VIOLATIONS + 1))
            fi
        done
    done < "$filepath"
}

# Scan AGENTS.md, docs/, .agents/skills/
[ -f "AGENTS.md" ] && check_file "AGENTS.md"
find docs -name "*.md" 2>/dev/null | while read -r f; do check_file "$f"; done
find .agents/skills -name "*.md" 2>/dev/null | while read -r f; do check_file "$f"; done

if [ "$VIOLATIONS" -gt 0 ]; then
    exit 1
fi
echo "All documentation cross-references are valid."'


    # --- Template: .github/workflows/pr.yml ---
    write_template ".github/workflows/pr.yml" '# generated by yoke
name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: {{install_command}}
      - name: Lint
        run: {{lint_command}}
      - name: Architecture lint
        run: bash scripts/lint_architecture.sh || true
      - name: Doc validation
        run: bash scripts/validate_docs.sh || true

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: {{install_command}}
      - name: Type check
        run: {{typecheck_command}}

  test:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: {{install_command}}
      - name: Test
        run: {{test_command}}'

    # --- Template: .github/workflows/ci.yml ---
    write_template ".github/workflows/ci.yml" '# generated by yoke
name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: {{install_command}}
      - name: Test with coverage
        run: {{test_command}}'

    # --- Template: .pre-commit-config.yaml ---
    write_template ".pre-commit-config.yaml" '# generated by yoke
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: {{lint_command}}
        language: system
        pass_filenames: false
      - id: format
        name: format
        entry: {{format_command}}
        language: system
        pass_filenames: false
      - id: typecheck
        name: typecheck
        entry: {{typecheck_command}}
        language: system
        pass_filenames: false
      - id: architecture-lint
        name: architecture lint
        entry: bash scripts/lint_architecture.sh
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: {{test_command}}
        language: system
        pass_filenames: false
        stages: [pre-push]'


    # --- Template: AGENTS.md ---
    write_template "AGENTS.md" '<!-- generated by yoke -->
# AI Agent Instructions for {{repo_name}}

> **Critical**: You are a principal software engineer working on {{repo_name}}. Your job: build features incrementally using test-first development.

## Quick Start

```bash
# 1. Install dependencies
{{install_command}}

# 2. Setup environment
cp .env.example .env
# Edit .env with required API keys

# 3. Start development
{{run_command}}
```

## Golden Rules

1. **GitHub Issue First** - No work without an issue. Create one if missing.
2. **Tests Before Code** - Write tests first, then implement.
3. **One Issue Per Session** - Each worktree session handles exactly ONE issue.
4. **One Thing At A Time** - Single feature per PR, focused commits.
5. **No Secrets** - Use environment variables, never hardcode credentials.
6. **Debug Efficiently** - Run tests once, save output, analyze. Never run full test suite repeatedly.

See [docs/dev/tdd-flow.md](docs/dev/tdd-flow.md) for detailed workflow. For code invariants, see [docs/principles.md](docs/principles.md).

## Architecture Overview

{{architecture_table}}

See [docs/architecture/overview.md](docs/architecture/overview.md) for full architecture details.

## Pre-Flight Checks

```bash
pwd
git remote get-url origin
git status
git branch --show-current
```

## Development Flow

Use the slash commands to drive the workflow:

- `/plan-feature <description>` — Decompose a feature into agent-sized GitHub issues with dependency ordering. Human-in-the-loop approval before issue creation.
- `/start-issue <number>` — Preflight, fetch issue, create branch, create plan, scaffold tests, verify tests run, trigger code review.
- `/create-pr` — Run tests + lint + typecheck, commit, push, create PR, trigger code review, report completion.
- `/fix-issue <number>` — Fetch issue, analyze, find relevant code, create branch, write test first, implement fix, create PR.

**Plan First**: The PreToolUse hook enforces this — code writes are blocked until a plan file exists in `docs/plans/`.

See [docs/dev/tdd-flow.md](docs/dev/tdd-flow.md) for the TDD workflow details and grind loop configuration.

## Code Review Flow

The `/start-issue` and `/create-pr` commands trigger code review automatically. If working manually:

1. Trigger code review using the code-reviewer subagent
2. Fix any Critical/High issues the reviewer identifies
3. Repeat until reviewer says "Ready to merge"
4. Only then create PR

> Code review is mandatory. Do not skip it.

## Testing

See [docs/dev/testing.md](docs/dev/testing.md) for test structure and patterns.

## Conventions

- Commits: single-line conventional format
- See [docs/dev/commit-conventions.md](docs/dev/commit-conventions.md) for full conventions.

## Skills & Tasks

{{skills_table}}

## Never Do This

- Code without tests
- Hardcode API keys or secrets
- Skip test verification
- Large multi-feature PRs
- Run full test suite repeatedly to debug
- Hardcode GitHub repo owner/name
- Place real trades in test mode

## Worktree Management

You are working in a **git worktree** - an isolated workspace. One worktree = One issue = One session.

## GitHub Operations

See [docs/dev/github-operations.md](docs/dev/github-operations.md) for `gh` CLI reference.

---

**Remember**: Tests first, small changes, always reference issues.'

    # --- Static: docs/INDEX.md ---
    write_file "docs/INDEX.md" '<!-- generated by yoke -->
# Documentation

## Quick Links

- [AGENTS.md](../AGENTS.md) - AI Agent instructions (start here for agents)
- [README.md](../README.md) - Project overview and setup

## Architecture

- [Architecture Overview](architecture/overview.md) - Domain map, layering, import rules
- [ADRs](architecture/decisions/) - Architecture decision records

## Development Procedures

- [TDD Workflow](dev/tdd-flow.md) - Test-driven development process
- [Commit Conventions](dev/commit-conventions.md) - Commit format, branch naming
- [Debugging](dev/debugging.md) - Debugging procedures
- [GitHub Operations](dev/github-operations.md) - `gh` CLI usage
- [Testing](dev/testing.md) - Test structure and patterns
- [Common Mistakes](dev/common-mistakes.md) - Recurring agent errors and fixes

## Plans

- [Plan Template](templates/plan-template.md) - Template for new issue plans

## Enforcement & Automation

- `scripts/lint_architecture.sh` - Architecture boundary linter
- `scripts/validate_docs.sh` - Doc cross-reference validation
- `scripts/audit_principles.sh` - Golden principles audit
- `.agents/config.yaml` - Shared grind loop config
- `.agents/hooks/check-completion.sh` - Grind loop completion checker
- `.agents/hooks/check-plan-exists.sh` - Plan-first workflow enforcement
- `.agents/hooks/opencode-grind-loop.sh` - Bash grind loop wrapper

## Skills

See `.agents/skills/` for specialized skills.

## Commands

- `/plan-feature <description>` — Decompose a feature into agent-sized issues with dependency ordering
- `/start-issue <number>` — Start work on a GitHub issue
- `/create-pr` — Create a pull request after completing work
- `/fix-issue <number>` — Quick-fix an issue with TDD'


    # --- Template: docs/dev/tdd-flow.md ---
    write_template "docs/dev/tdd-flow.md" '<!-- generated by yoke -->
# TDD Workflow

## Standard TDD Flow

```bash
# 1. Write test in tests/
# 2. Verify test fails
{{test_command}}

# 3. Implement minimal code to pass
# 4. Verify test passes
{{test_command}}

# 5. Commit
git add <test_file> <source_file>
git commit -m "feat(scope): implement feature for #XX"
```

## Completing a Feature

Run `/create-pr` — it handles tests, lint, typecheck, commit, push, PR creation, and code review trigger in one shot.

See [`.agents/commands/create-pr.md`](../../.agents/commands/create-pr.md) for the full step-by-step breakdown.

## Grind Loop (Iterate-Until-Done)

### Configuration

All grind loop settings live in `.agents/config.yaml`:

```yaml
grind_loop:
  max_iterations: 5
  stall_timeout_seconds: 300
  idle_timeout_seconds: 120
  session_log: .agents/session-log.jsonl
```

### Claude Code

Enforcement is automatic via hooks in `.claude/settings.local.json`:
- `Stop` hook runs `.agents/hooks/check-completion.sh` after each agent turn
- `PreToolUse` hook runs `.agents/hooks/check-plan-exists.sh` before any Write/Edit

### OpenCode

Enforcement is automatic via plugins in `.opencode/plugins/`:
- `grind-loop.ts` — listens to `session.idle` events, runs `check-completion.sh`, re-prompts if incomplete
- `plan-first.ts` — intercepts `tool.execute.before` on write/edit tools

Fallback: `.agents/hooks/opencode-grind-loop.sh` wraps `opencode --prompt` in a bash loop.

### Completion Criteria (shared)

Both tools use `.agents/hooks/check-completion.sh` which checks:
1. Tests pass (`{{test_command}}`)
2. No Critical/High findings in `CODE_REVIEW_*.md`
3. Blind review requested if PR exists but no review file
4. Scratchpad signals DONE
5. Agent idle detection with stuck loop escalation
6. Iteration cap (configurable, default 5)

### Scratchpad

Maintain `.agents/scratchpad.md` during work with STATUS, ITERATION, COMPLETED checklist, CURRENT_FOCUS, and BLOCKERS.

### Stall & Idle Protection

| Scenario | Detection | Action |
|---|---|---|
| Agent stuck (no output) | Bash: `timeout`. OpenCode: stall timer. | Kill/re-prompt |
| Agent stopped but not done | check-completion.sh idle check | Re-prompt with context |
| Same task stuck across iterations | Session log analysis | Escalated re-prompt |
| Max iterations reached | Iteration counter | Stop gracefully |'

    # --- Static: docs/dev/commit-conventions.md ---
    write_file "docs/dev/commit-conventions.md" '<!-- generated by yoke -->
# Commit Conventions

## Commit Message Format

Follow conventional commits with **single-line format only**:

```bash
git commit -m "feat(scope): implement feature for #XX"
```

## Commit Types

- `feat(scope): add feature for #XX`
- `fix(scope): correct bug for #XX`
- `docs(scope): update documentation for #XX`
- `test(scope): add tests for #XX`
- `refactor(scope): simplify logic for #XX`
- `chore(scope): update dependencies for #XX`

## Branch Naming

- `feature/issue-XX-short-description`
- `fix/issue-XX-short-description`

## Pre-Commit Checklist

- [ ] GitHub issue exists and referenced (`#XX`)
- [ ] Test written BEFORE implementation
- [ ] All tests pass
- [ ] Linting clean
- [ ] Formatting applied
- [ ] Type checking passes
- [ ] Commit follows conventional format
- [ ] No hardcoded secrets
- [ ] Single focused change only'

    # --- Template: docs/dev/common-mistakes.md ---
    write_template "docs/dev/common-mistakes.md" '<!-- generated by yoke -->
# Common Mistakes

## Architecture

- **Cross-layer imports**: Do not import from inner layers into outer layers. Respect the architecture boundaries.
- **Inline templates in skills**: Skills should reference files, not contain inline code templates.

## Testing

- **Running full test suite repeatedly**: Run once, save output, analyze. Do not re-run the full suite to debug.
- **Not mocking external APIs**: Always mock external API calls in tests.
- **Random test data**: Use deterministic test data, not random values.

## Git / Workflow

- **Hardcoding repo owner/name**: Always derive from `git remote get-url origin`.
- **Starting new issue in same session**: One worktree = one issue = one session.
- **Multi-feature PRs**: One feature per PR, focused commits.
- **Skipping code review**: Code review is mandatory before merge.

## Security

- **Hardcoded secrets**: Use environment variables for all credentials.
- **Committed .env files**: Never commit .env files with real credentials.'

    # --- Template: docs/dev/github-operations.md ---
    write_template "docs/dev/github-operations.md" '<!-- generated by yoke -->
# GitHub Operations

## Getting Repo Info

```bash
# Get owner/repo from git remote (CRITICAL — never hardcode)
git remote get-url origin
```

## Issue Management

```bash
gh issue view <number> --repo <owner>/<repo>
gh issue create --repo <owner>/<repo> --title "title" --body "body"
gh issue edit <number> --repo <owner>/<repo> --add-label "label"
gh issue close <number> --repo <owner>/<repo>
```

## Pull Requests

```bash
gh pr create --repo <owner>/<repo> --title "title" --head <branch> --base main --body "body"
gh pr view <number> --repo <owner>/<repo>
gh pr diff <number> --repo <owner>/<repo>
gh pr merge <number> --repo <owner>/<repo> --squash
gh pr checks <number> --repo <owner>/<repo>
```

## Branch Management

```bash
git checkout -b feature/issue-XX-description
git push -u origin feature/issue-XX-description
```

## Search

```bash
gh issue list --repo <owner>/<repo> --label "label" --state open
gh pr list --repo <owner>/<repo> --state open
```'

    # --- Static: docs/templates/plan-template.md ---
    write_file "docs/templates/plan-template.md" '<!-- generated by yoke -->
# Plan: Issue #NUMBER — TITLE

## Goal

_One sentence describing what this change accomplishes._

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2

## Files to Modify

| File | Change |
|---|---|
| `path/to/file` | Description of change |

## Test Scenarios

| Scenario | Expected |
|---|---|
| Happy path | ... |
| Edge case | ... |

## Risks

- Risk 1: mitigation'

    # --- Static: docs/architecture/decisions/adr-template.md ---
    write_file "docs/architecture/decisions/adr-template.md" '<!-- generated by yoke -->
# ADR-NNN: Title

## Status

Proposed | Accepted | Deprecated | Superseded by ADR-NNN

## Context

What is the issue that we are seeing that is motivating this decision or change?

## Decision

What is the change that we are proposing and/or doing?

## Consequences

What becomes easier or more difficult to do because of this change?'

    # --- Static: docs/architecture/decisions/adr-001-agentic-harness.md ---
    write_file "docs/architecture/decisions/adr-001-agentic-harness.md" '<!-- generated by yoke -->
# ADR-001: Adopt Agentic Development Harness

## Status

Accepted

## Context

AI coding agents (Claude Code, OpenCode, Codex, Kiro) can autonomously work on GitHub issues, but without structure they produce inconsistent results: missing tests, no code review, unbounded iteration, and no observability.

We need a standardized harness that enforces quality gates (plan-first, test-first, code review), provides iteration control (grind loop with completion checking), and supports parallel issue dispatch with worktree isolation.

## Decision

Adopt the three-layer agentic development harness (Yoke):

- **Layer 1 (Outer Orchestration)**: Parallel issue dispatch, worktree isolation, monitoring, auto-merge
- **Layer 2 (Agentic Loop)**: Grind loop, plan-first enforcement, completion checking, code review, commands, shared config
- **Layer 3 (Inner Knowledge)**: Documentation structure, AGENTS.md, domain-specific skills, plan templates, principles

The harness uses shared shell scripts for tool-agnostic logic and tool-native implementations (Claude hooks, OpenCode plugins, Kiro hooks) for agent-specific integration.

## Consequences

- Agents must create a plan before writing code (enforced by PreToolUse hook)
- All agent sessions iterate until completion criteria are met (grind loop)
- Code review is mandatory before PR creation
- Multiple issues can be dispatched in parallel with dependency resolution
- New agent tools can be supported by adding an adapter without modifying existing components'

}


# ============================================================================
# LAYER 1 — FULL PROFILE (only full gets these)
# ============================================================================

