install_layer1_full() {
    echo ""
    echo "=== Layer 1: Outer orchestration (full) ==="

    # --- Directories ---
    create_dir ".github/ISSUE_TEMPLATE"
    create_dir ".github/workflows"

    # --- Template: scripts/orchestrate.sh ---
    write_template "scripts/orchestrate.sh" '#!/usr/bin/env bash
# generated by yoke
# orchestrate.sh — Parallel issue orchestrator
#
# Discovers issues, resolves dependencies (topological sort), dispatches agents
# to worktrees in waves, monitors progress, and auto-merges eligible PRs.
#
# Usage:
#   scripts/orchestrate.sh --label orchestrator-ready
#   scripts/orchestrate.sh --issues 101,102,103
#   scripts/orchestrate.sh --dry-run --label orchestrator-ready
#   scripts/orchestrate.sh --max-parallel 2 --issues 101,102

set -euo pipefail

# --- Derive repo info from git remote ---
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
if [ -z "$REMOTE_URL" ]; then
    echo "ERROR: No git remote found. Cannot determine owner/repo."
    exit 1
fi
OWNER=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\1#'"'"')
REPO=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\2#'"'"')

# --- Config ---
CONFIG_FILE=".agents/config.yaml"
read_config() {
    local key="$1" default="$2"
    if [ -f "$CONFIG_FILE" ]; then
        local value
        value=$(grep -E "^\s+${key}:" "$CONFIG_FILE" 2>/dev/null | head -1 | sed '"'"'s/.*:\s*//'"'"' | tr -d '"'"'"'"'"' | tr -d "'"'"'"'"'"' || echo "")
        [ -n "$value" ] && echo "$value" && return
    fi
    echo "$default"
}

MAX_PARALLEL=$(read_config max_parallel 3)
POLL_INTERVAL=$(read_config poll_interval_seconds 60)
STALL_MULTIPLIER=$(read_config stall_detection_multiplier 2)
ORCH_LOG=$(read_config log ".agents/orchestrator-log.jsonl")
AUTO_MERGE_METHOD=$(read_config auto_merge_method "squash")
DEFAULT_AGENT_TOOL=$(read_config default_agent_tool "{{default_agent_tool}}")
DEFAULT_LABEL=$(read_config default_label "orchestrator-ready")
KILL_GRACE=$(read_config kill_grace_seconds 5)
STALL_TIMEOUT=$(read_config stall_timeout_seconds 300)
LOCKFILE=".agents/orchestrator.lock"

# --- CLI args ---
LABEL=""
ISSUES=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --label) LABEL="${2:-$DEFAULT_LABEL}"; shift 2 ;;
        --issues) ISSUES="$2"; shift 2 ;;
        --max-parallel) MAX_PARALLEL="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [ -z "$LABEL" ] && [ -z "$ISSUES" ]; then
    LABEL="$DEFAULT_LABEL"
fi

# --- Lockfile ---
if [ -f "$LOCKFILE" ]; then
    LOCK_PID=$(cat "$LOCKFILE" 2>/dev/null || echo "")
    if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null; then
        echo "ERROR: Another orchestrator is running (PID $LOCK_PID)"
        exit 1
    fi
    rm -f "$LOCKFILE"
fi
echo $$ > "$LOCKFILE"
trap '"'"'rm -f "$LOCKFILE"'"'"' EXIT

# --- Logging ---
log_event() {
    local event="$1" data="${2:-{}}"
    local ts
    ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "{\"timestamp\":\"$ts\",\"event\":\"$event\",\"data\":$data}" >> "$ORCH_LOG" 2>/dev/null || true
}

log_event "orchestrator_start" "{\"label\":\"$LABEL\",\"issues\":\"$ISSUES\",\"max_parallel\":$MAX_PARALLEL}"

# --- Phase 1: Issue Discovery ---
echo "=== Phase 1: Issue Discovery ==="
declare -a ISSUE_NUMS=()
declare -A ISSUE_DATA=()

if [ -n "$ISSUES" ]; then
    IFS='"'"','"'"' read -ra ISSUE_NUMS <<< "$ISSUES"
else
    while IFS= read -r num; do
        [ -n "$num" ] && ISSUE_NUMS+=("$num")
    done < <(gh issue list --repo "$OWNER/$REPO" --label "$LABEL" --state open --json number --jq '"'"'.[].number'"'"' 2>/dev/null)
fi

echo "Found ${#ISSUE_NUMS[@]} issue(s)"

# Run preflight on each
declare -a READY_ISSUES=()
for num in "${ISSUE_NUMS[@]}"; do
    local_json=$(bash scripts/issue-preflight.sh "$num" 2>/dev/null) || true
    ready=$(echo "$local_json" | jq -r '"'"'.ready // false'"'"' 2>/dev/null || echo "false")
    if [ "$ready" = "true" ]; then
        READY_ISSUES+=("$num")
        ISSUE_DATA["$num"]="$local_json"
    else
        reason=$(echo "$local_json" | jq -r '"'"'.block_reason // "unknown"'"'"' 2>/dev/null || echo "unknown")
        echo "  Issue #$num blocked: $reason"
        log_event "issue_blocked" "{\"issue\":$num,\"reason\":\"$reason\"}"
    fi
done

echo "${#READY_ISSUES[@]} issue(s) ready"

if [ ${#READY_ISSUES[@]} -eq 0 ]; then
    echo "No issues ready. Exiting."
    log_event "orchestrator_end" "{\"reason\":\"no_ready_issues\"}"
    exit 0
fi

# --- Phase 2: Dependency Resolution (Kahn'"'"'s algorithm) ---
echo ""
echo "=== Phase 2: Dependency Resolution ==="

declare -A DEPS=()
declare -A IN_DEGREE=()
for num in "${READY_ISSUES[@]}"; do
    deps=$(echo "${ISSUE_DATA[$num]}" | jq -r '"'"'.depends_on // ""'"'"' 2>/dev/null || echo "")
    DEPS["$num"]="$deps"
    IN_DEGREE["$num"]=0
done

for num in "${READY_ISSUES[@]}"; do
    IFS='"'"','"'"' read -ra dep_list <<< "${DEPS[$num]}"
    for dep in "${dep_list[@]}"; do
        dep=$(echo "$dep" | tr -d '"'"' #'"'"')
        [ -z "$dep" ] || [ "$dep" = "none" ] && continue
        if [[ -v IN_DEGREE["$num"] ]]; then
            IN_DEGREE["$num"]=$(( ${IN_DEGREE[$num]} + 1 ))
        fi
    done
done

# Build waves
declare -a WAVES=()
declare -A PROCESSED=()
remaining=${#READY_ISSUES[@]}
wave_num=0

while [ "$remaining" -gt 0 ]; do
    wave_num=$((wave_num + 1))
    local_wave=""
    for num in "${READY_ISSUES[@]}"; do
        [[ -v PROCESSED["$num"] ]] && continue
        if [ "${IN_DEGREE[$num]:-0}" -eq 0 ]; then
            [ -n "$local_wave" ] && local_wave+=","
            local_wave+="$num"
            PROCESSED["$num"]=1
            remaining=$((remaining - 1))
        fi
    done

    if [ -z "$local_wave" ]; then
        echo "ERROR: Dependency cycle detected among remaining issues"
        log_event "cycle_detected" "{\"remaining\":$remaining}"
        exit 1
    fi

    WAVES+=("$local_wave")
    echo "  Wave $wave_num: $local_wave"

    # Reduce in-degrees for next wave
    IFS='"'"','"'"' read -ra wave_issues <<< "$local_wave"
    for done_num in "${wave_issues[@]}"; do
        for num in "${READY_ISSUES[@]}"; do
            [[ -v PROCESSED["$num"] ]] && continue
            IFS='"'"','"'"' read -ra dep_list <<< "${DEPS[$num]}"
            for dep in "${dep_list[@]}"; do
                dep=$(echo "$dep" | tr -d '"'"' #'"'"')
                if [ "$dep" = "$done_num" ]; then
                    IN_DEGREE["$num"]=$(( ${IN_DEGREE[$num]} - 1 ))
                fi
            done
        done
    done
done

if [ "$DRY_RUN" = true ]; then
    echo ""
    echo "=== DRY RUN — Wave plan above. No agents launched. ==="
    log_event "orchestrator_end" "{\"reason\":\"dry_run\",\"waves\":$wave_num}"
    exit 0
fi

# --- Phase 3: Dispatch + Monitor ---
echo ""
echo "=== Phase 3: Dispatch + Monitor ==="

declare -A OUTCOMES=()

for wave_idx in "${!WAVES[@]}"; do
    wave="${WAVES[$wave_idx]}"
    echo ""
    echo "--- Wave $((wave_idx + 1))/${#WAVES[@]}: $wave ---"

    IFS='"'"','"'"' read -ra wave_issues <<< "$wave"
    declare -A PIDS=()
    declare -A WORKTREES=()

    # Limit parallelism within wave
    active=0
    for num in "${wave_issues[@]}"; do
        while [ "$active" -ge "$MAX_PARALLEL" ]; do
            sleep "$POLL_INTERVAL"
            for pid_num in "${!PIDS[@]}"; do
                if ! kill -0 "${PIDS[$pid_num]}" 2>/dev/null; then
                    wait "${PIDS[$pid_num]}" 2>/dev/null || true
                    unset "PIDS[$pid_num]"
                    active=$((active - 1))
                fi
            done
        done

        agent_tool=$(echo "${ISSUE_DATA[$num]}" | jq -r '"'"'.agent_tool // "'"'"'"$DEFAULT_AGENT_TOOL"'"'"'"'"'"' 2>/dev/null || echo "$DEFAULT_AGENT_TOOL")
        wt_dir="worktrees/issue-$num"

        echo "  Launching issue #$num with $agent_tool..."
        log_event "issue_start" "{\"issue\":$num,\"agent_tool\":\"$agent_tool\"}"

        bash scripts/wti.sh "$num" --setup-only 2>/dev/null || true
        WORKTREES["$num"]="$wt_dir"

        (
            cd "$wt_dir" 2>/dev/null || exit 1
            case "$agent_tool" in
                claude)
                    claude --prompt "Run /start-issue $num" 2>/dev/null || true
                    ;;
                opencode)
                    source .agents/hooks/opencode-grind-loop.sh
                    grind_loop "Run /start-issue $num" 2>/dev/null || true
                    ;;
                *)
                    source .agents/hooks/opencode-grind-loop.sh
                    grind_loop "Run /start-issue $num" 2>/dev/null || true
                    ;;
            esac
        ) &
        PIDS["$num"]=$!
        active=$((active + 1))
    done

    # Wait for all in wave with stall detection
    STALL_LIMIT=$((STALL_TIMEOUT * STALL_MULTIPLIER))
    for num in "${!PIDS[@]}"; do
        local_start=$(date +%s)
        while kill -0 "${PIDS[$num]}" 2>/dev/null; do
            sleep "$POLL_INTERVAL"
            elapsed=$(( $(date +%s) - local_start ))
            if [ "$elapsed" -gt "$STALL_LIMIT" ]; then
                echo "  Issue #$num stalled (${elapsed}s). Killing."
                log_event "issue_stalled" "{\"issue\":$num,\"elapsed\":$elapsed}"
                kill -TERM "${PIDS[$num]}" 2>/dev/null || true
                sleep "$KILL_GRACE"
                kill -KILL "${PIDS[$num]}" 2>/dev/null || true
                break
            fi
        done
        wait "${PIDS[$num]}" 2>/dev/null
        local_exit=$?

        if [ "$local_exit" -eq 0 ]; then
            OUTCOMES["$num"]="success"
            log_event "issue_complete" "{\"issue\":$num,\"status\":\"success\"}"

            # Auto-merge if eligible
            auto_merge=$(echo "${ISSUE_DATA[$num]}" | jq -r '"'"'.auto_merge // false'"'"' 2>/dev/null || echo "false")
            if [ "$auto_merge" = "true" ] || [ "$auto_merge" = "yes" ]; then
                pr_num=$(gh pr list --repo "$OWNER/$REPO" --head "feature/issue-$num-*" --json number --jq '"'"'.[0].number'"'"' 2>/dev/null || echo "")
                if [ -n "$pr_num" ]; then
                    echo "  Auto-merging PR #$pr_num for issue #$num"
                    gh pr merge "$pr_num" --repo "$OWNER/$REPO" --"$AUTO_MERGE_METHOD" 2>/dev/null || true
                    log_event "auto_merge" "{\"issue\":$num,\"pr\":$pr_num}"
                fi
            fi
        else
            OUTCOMES["$num"]="failed"
            log_event "issue_complete" "{\"issue\":$num,\"status\":\"failed\",\"exit_code\":$local_exit}"
        fi

        # Cleanup worktree
        bash scripts/wtr.sh "$num" 2>/dev/null || true
    done

    # Update main between waves
    if [ "$((wave_idx + 1))" -lt "${#WAVES[@]}" ]; then
        echo "  Updating main before next wave..."
        git fetch origin main 2>/dev/null || true
        git checkout main 2>/dev/null && git pull origin main 2>/dev/null || true
    fi
done

# --- Phase 4: Summary ---
echo ""
echo "=== Phase 4: Summary ==="
for num in "${READY_ISSUES[@]}"; do
    echo "  Issue #$num: ${OUTCOMES[$num]:-unknown}"
done
log_event "orchestrator_end" "{\"total\":${#READY_ISSUES[@]}}"
echo ""
echo "Done."'


    # --- Template: scripts/wti.sh ---
    write_template "scripts/wti.sh" '#!/usr/bin/env bash
# generated by yoke
# wti.sh — Worktree Issue Init (portable, uses native git worktree)
#
# Creates a git worktree for an issue, installs dependencies, sets up agent links.
#
# Usage:
#   scripts/wti.sh <issue_number> [-o|-c|--setup-only]
#
# Flags:
#   -o          Launch with OpenCode after setup
#   -c          Launch with Claude Code after setup
#   --setup-only  Create worktree but do not launch agent

set -euo pipefail

ISSUE_NUM="${1:-}"
if [ -z "$ISSUE_NUM" ]; then
    echo "Usage: scripts/wti.sh <issue_number> [-o|-c|--setup-only]"
    exit 1
fi
shift

AGENT_TOOL=""
SETUP_ONLY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        -o) AGENT_TOOL="opencode"; shift ;;
        -c) AGENT_TOOL="claude"; shift ;;
        --setup-only) SETUP_ONLY=true; shift ;;
        *) shift ;;
    esac
done

# Derive branch and worktree path
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
OWNER=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\1#'"'"')
REPO=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\2#'"'"')

ISSUE_TITLE=$(gh issue view "$ISSUE_NUM" --repo "$OWNER/$REPO" --json title --jq '"'"'.title'"'"' 2>/dev/null || echo "task")
SHORT_DESC=$(echo "$ISSUE_TITLE" | tr '"'"'[:upper:]'"'"' '"'"'[:lower:]'"'"' | sed '"'"'s/[^a-z0-9]/-/g'"'"' | sed '"'"'s/--*/-/g'"'"' | cut -c1-30 | sed '"'"'s/-$//'"'"')
BRANCH="feature/issue-${ISSUE_NUM}-${SHORT_DESC}"
WT_DIR="../worktrees/issue-${ISSUE_NUM}"
PRIMARY_DIR="$(pwd)"

echo "=== Creating worktree for issue #$ISSUE_NUM ==="
echo "  Branch:    $BRANCH"
echo "  Worktree:  $WT_DIR"

# Create worktree
git worktree add "$WT_DIR" -b "$BRANCH" 2>/dev/null || git worktree add "$WT_DIR" "$BRANCH" 2>/dev/null || {
    echo "ERROR: Failed to create worktree"
    exit 1
}

# Post-create lifecycle
cd "$WT_DIR"

# Copy .env from primary worktree
if [ -f "$PRIMARY_DIR/.env" ]; then
    cp "$PRIMARY_DIR/.env" .env
    echo "  Copied .env"
fi

# Install dependencies
echo "  Installing dependencies..."
{{install_command}} 2>/dev/null || true

# Setup agent links
if [ -f scripts/setup-agent-links.sh ]; then
    bash scripts/setup-agent-links.sh 2>/dev/null || true
fi

echo "  Worktree ready."

if [ "$SETUP_ONLY" = true ]; then
    echo "  Setup only — not launching agent."
    exit 0
fi

# Launch agent
case "$AGENT_TOOL" in
    opencode)
        echo "  Launching OpenCode..."
        source .agents/hooks/opencode-grind-loop.sh
        grind_loop "Run /start-issue $ISSUE_NUM"
        ;;
    claude)
        echo "  Launching Claude Code..."
        claude --prompt "Run /start-issue $ISSUE_NUM"
        ;;
    *)
        echo "  No agent specified. Use -o (OpenCode) or -c (Claude) to launch."
        echo "  Or run manually: cd $WT_DIR"
        ;;
esac'

    # --- Template: scripts/wtr.sh ---
    write_template "scripts/wtr.sh" '#!/usr/bin/env bash
# generated by yoke
# wtr.sh — Worktree Remove (portable, uses native git worktree)
#
# Removes a worktree for an issue, optionally merging the branch first.
#
# Usage:
#   scripts/wtr.sh <issue_number> [-m]
#
# Flags:
#   -m    Merge branch into main before removal

set -euo pipefail

ISSUE_NUM="${1:-}"
if [ -z "$ISSUE_NUM" ]; then
    echo "Usage: scripts/wtr.sh <issue_number> [-m]"
    exit 1
fi
shift

MERGE=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        -m) MERGE=true; shift ;;
        *) shift ;;
    esac
done

WT_DIR="../worktrees/issue-${ISSUE_NUM}"

if [ ! -d "$WT_DIR" ]; then
    echo "Worktree not found: $WT_DIR"
    exit 1
fi

BRANCH=$(cd "$WT_DIR" && git branch --show-current 2>/dev/null || echo "")

if [ "$MERGE" = true ] && [ -n "$BRANCH" ]; then
    echo "Merging $BRANCH into main..."
    git checkout main 2>/dev/null || true
    git merge "$BRANCH" --no-edit 2>/dev/null || {
        echo "WARNING: Merge failed. Resolve conflicts manually."
    }
fi

echo "Removing worktree for issue #$ISSUE_NUM..."
git worktree remove "$WT_DIR" --force 2>/dev/null || rm -rf "$WT_DIR"
git worktree prune 2>/dev/null || true

if [ -n "$BRANCH" ]; then
    git branch -d "$BRANCH" 2>/dev/null || true
fi

echo "Done."'

    # --- Static: scripts/issue-preflight.sh ---
    write_file "scripts/issue-preflight.sh" '#!/usr/bin/env bash
# generated by yoke
# issue-preflight.sh — Single-issue validation and Agent Metadata parsing
#
# Exit codes:
#   0 = ready
#   1 = blocked
#   2 = not found
#
# Output: JSON with issue metadata and readiness status

set -euo pipefail

ISSUE_NUM="${1:-}"
if [ -z "$ISSUE_NUM" ]; then
    echo "Usage: scripts/issue-preflight.sh <issue_number>"
    exit 2
fi

REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
OWNER=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\1#'"'"')
REPO=$(echo "$REMOTE_URL" | sed -E '"'"'s#.*[:/]([^/]+)/([^/.]+)(\.git)?$#\2#'"'"')

# Fetch issue
ISSUE_JSON=$(gh issue view "$ISSUE_NUM" --repo "$OWNER/$REPO" --json title,body,state 2>/dev/null) || {
    echo "{\"ready\":false,\"block_reason\":\"Issue #$ISSUE_NUM not found\"}"
    exit 2
}

STATE=$(echo "$ISSUE_JSON" | jq -r '"'"'.state'"'"')
TITLE=$(echo "$ISSUE_JSON" | jq -r '"'"'.title'"'"')
BODY=$(echo "$ISSUE_JSON" | jq -r '"'"'.body // ""'"'"')

if [ "$STATE" != "OPEN" ]; then
    echo "{\"ready\":false,\"block_reason\":\"Issue #$ISSUE_NUM is $STATE, not OPEN\"}"
    exit 1
fi

# Check for existing PR
EXISTING_PR=$(gh pr list --repo "$OWNER/$REPO" --search "issue $ISSUE_NUM" --json number --jq '"'"'.[0].number // empty'"'"' 2>/dev/null || echo "")
if [ -n "$EXISTING_PR" ]; then
    echo "{\"ready\":false,\"block_reason\":\"PR #$EXISTING_PR already exists for issue #$ISSUE_NUM\"}"
    exit 1
fi

# Parse Agent Metadata table from issue body
parse_meta() {
    local field="$1" default="$2"
    local value
    value=$(echo "$BODY" | grep -i "| *$field *|" 2>/dev/null | sed '"'"'s/.*| *//;s/ *|.*//'"'"' | tr -d '"'"' '"'"' || echo "")
    [ -n "$value" ] && echo "$value" || echo "$default"
}

DEPENDS_ON=$(parse_meta "Depends on" "#none")
PARALLEL_SAFE=$(parse_meta "Parallel safe" "yes")
AUTO_MERGE=$(parse_meta "Auto-merge" "no")
AGENT_TOOL=$(parse_meta "Agent tool" "opencode")
COMPLEXITY=$(parse_meta "Estimated complexity" "small")

# Check dependencies
READY=true
BLOCK_REASON=""
if [ "$DEPENDS_ON" != "#none" ] && [ "$DEPENDS_ON" != "none" ] && [ -n "$DEPENDS_ON" ]; then
    IFS='"'"','"'"' read -ra DEP_LIST <<< "$DEPENDS_ON"
    for dep in "${DEP_LIST[@]}"; do
        dep_num=$(echo "$dep" | tr -d '"'"' #'"'"')
        [ -z "$dep_num" ] && continue
        dep_pr=$(gh pr list --repo "$OWNER/$REPO" --search "closes #$dep_num" --state merged --json number --jq '"'"'.[0].number // empty'"'"' 2>/dev/null || echo "")
        if [ -z "$dep_pr" ]; then
            READY=false
            BLOCK_REASON="Dependency #$dep_num has no merged PR"
            break
        fi
    done
fi

cat <<ENDJSON
{
  "issue_number": $ISSUE_NUM,
  "title": "$(echo "$TITLE" | sed '"'"'s/"/\\"/g'"'"')",
  "depends_on": "$DEPENDS_ON",
  "parallel_safe": $([ "$PARALLEL_SAFE" = "yes" ] && echo "true" || echo "false"),
  "auto_merge": $([ "$AUTO_MERGE" = "yes" ] && echo "true" || echo "false"),
  "agent_tool": "$AGENT_TOOL",
  "complexity": "$COMPLEXITY",
  "ready": $READY,
  "block_reason": "$BLOCK_REASON"
}
ENDJSON

$READY && exit 0 || exit 1'

    # --- Static: .github/ISSUE_TEMPLATE/feature-task.md ---
    write_file ".github/ISSUE_TEMPLATE/feature-task.md" '---
name: Feature Task
about: A task for agent-driven development
title: ""
labels: orchestrator-ready
---

## Description

_Describe the feature or task._

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2

## Agent Metadata

| Field                | Value    |
| -------------------- | -------- |
| Depends on           | #none    |
| Parallel safe        | yes      |
| Auto-merge           | no       |
| Agent tool           | opencode |
| Estimated complexity | small    |'

}


# ============================================================================
# GITIGNORE MANAGEMENT
# ============================================================================

install_gitignore() {
    echo ""
    echo "=== Gitignore entries ==="
    append_gitignore ".agents/session-log.jsonl"
    append_gitignore ".agents/orchestrator-log.jsonl"
    append_gitignore ".agents/orchestrator.lock"
    append_gitignore ".agents/scratchpad.md"
    append_gitignore "CODE_REVIEW_*.md"
    append_gitignore "test-output.txt"
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

echo "Yoke install.sh — profile: $PROFILE"
echo ""

# Profile containment: minimal ⊂ standard ⊂ full
install_layer2_minimal

case "$PROFILE" in
    standard|full)
        install_layer2_standard
        ;;
esac

case "$PROFILE" in
    full)
        install_layer1_full
        ;;
esac

install_gitignore

# Make shell scripts executable
find .agents/hooks -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true
find scripts -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true

echo ""
echo "Created $CREATED files ($TEMPLATES templates with placeholders), skipped $SKIPPED existing"
echo ""
echo "Next steps:"
echo "  1. The agent will detect your toolchain and fill in {{placeholders}}"
echo "  2. The agent will generate tool-native components for your selected agent tools"
echo "  3. The agent will analyze your codebase and generate Layer 3 content"
